### ISSUE TITLE
Bad font / metrics chosen for "Im Palmenstuck"

### ISSUE THREAD

**Issue by pirmin** [sumatrapdfreader/sumatrapdf#1129]
here the String "Im Palmenstück" is rendered too big; it shows correctly in Chrome Preview and Foxit Reader;
[briefkasten.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2851543/briefkasten.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk all fonts appear to be better behaved in latest version. Without a specific illustration I suggest this issue has now been addressed and can be closed

![Untitled1129](https://user-images.githubusercontent.com/12754913/68908708-00c06200-0744-11ea-939d-77cb8513309a.png)

**Comment by kjk** [comment]
That part looks better but the other text regressed ("Pirmin" is bold), so leaving for now.
Need to compare font substitution with 3.1.2.

**Comment by kjk** [comment]
Fully fixed now.

**Comment by pirmin** [comment]
hm, still not working with  SumatraPDF-prerelease-11403-64-install.exe
![sumatra_bug](https://user-images.githubusercontent.com/396373/69828846-cd8ad200-121d-11ea-809e-7c5f4baa7882.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
the font metrics for all lettering appears good the fault is in the background object 4 (is that lettering?)
![image](https://user-images.githubusercontent.com/12754913/71772995-2bad8200-2f4d-11ea-8ac9-bb2eb7a9197c.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
Just rechecking The problem persists however it is common with many other MuPDF font cases where on this occasion the oversized number 4 is poorly defined


Here I have re-defined the Helvetica-Bold 4 by name as standard Arial which is a native windows font and both Acrobat and SumatraPDF agree on how the 4 should be shown.[1129 briefkasten 4 windows.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6112150/1129.briefkasten.4.windows.pdf)
![image](https://user-images.githubusercontent.com/12754913/110556040-abc50e00-8135-11eb-98b8-7fb2621465da.png)

**Comment by kjk** [comment]
Reported to: https://bugs.ghostscript.com/show_bug.cgi?id=709329

Not going to keep it open because I'm not going to work on it.

If mupdf fixes it, we'll inherit the fix.

**Comment by kjk** [comment]
per mupdf, they won't fix it

**Comment by pirmin** [comment]
since I'm selling this house, it's no longer a problem for me

-- 
Pirmin Braun ***@***.*** +491749747584 
Pirmin Braun GmbH - www.mosella-erp.de - Im Palmenstück 4, 56072 Koblenz 
- 
HRB 26312 DE319238613

14.04.2026 17:07:39 Krzysztof Kowalczyk ***@***.***>:
