### ISSUE TITLE
Per Page Zoom

### ISSUE THREAD

**Issue by dbent** [sumatrapdfreader/sumatrapdf#1134]
I have some CBZ files where the images are (frustratingly) different resolutions. When viewed in **Book View** or **Facing** (two pages simultaneously) with a zoom of **Fit Page** or **Fit Content** this can be produce a weird effect because it appears the zoom level of the larger of the two pages is applied to both pages. Ideally, the zoom level of each page would be calculated independently. To better illustrate what I mean, see the attached [example.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/2889579/example.zip).

The first page is all red and has a resolution of 1080x1920, the second page is all green and has a resolution of 540x960, and the third page is all blue and has a resolution of 270x480. When viewed in **Single Page** with a zoom of **Fit Page** or **Fit Content** each page correctly occupies the entire screen. However, when viewed in **Book View** or **Facing** the next page is rendered significantly smaller:

![example.png](https://user-images.githubusercontent.com/1547727/53174811-ac26f680-35b8-11e9-8814-1a55173cb1d0.png)

Obviously, the actual differences in resolution aren't so drastic, that's merely to illustrate the issue, but the effect can still be annoying.

**Comment by GitHubRulesOK** [comment]
@kjk related to https://github.com/sumatrapdfreader/sumatrapdf/issues/152 , however this is an extra wrinkle of a rare case where two side by side pages need different zoom, not sure that many other users would need this. However from personal experience it can be common where a small page of tabular info is needed alongside a larger drawing sheet. Forcing to single page mode may be acceptable if there was a variable split screen with both following common zoom (width/height/full) ?

**Comment by SumatraPeter** [comment]
If #152 is fixed and we have per-page zoomReal, it should be possibly to zoom each page independently and appropriately _before_ they are joined together to be displayed in **Book View** or **Facing** mode.

**Comment by kjk** [comment]
Fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/48ba64ef4cadc656905026fa274dfb73d19d49aa

**Comment by sam892** [comment]
Close, however this only works when using "Show Pages Continuously".

I just tried the daily build to pick up the fix @kjk mentioned. I still have the problem @dbent illustrated when I use fit page on normal book view (i.e. without show pages continuously). Looking at [48ba64e](https://github.com/sumatrapdfreader/sumatrapdf/commit/48ba64ef4cadc656905026fa274dfb73d19d49aa) it says it's for continuous view.

May we have this extended so it works when showing just a single pair of pages, please?

**Comment by GitHubRulesOK** [comment]
Hi sam892
 I am not sure that the OP request is achievable (as it stands), do you have any other program in mind where two document pages of dissimilar size are scaled differently alongside each other in the same window.

SumatraPDF can apply different zoom widths sequentially thus it works in continuous mode, (and was closed as best endeavour) what is requested initially was 2 separate zoom "concurrently side by side" which would require split windows (which is unlikely to be introduced, definitely not soon)

**Comment by sam892** [comment]
Nothing else comes to mind; Sumatra in continuous mode with 48ba64e is the only one I know of.

I'd imagined that solved problem of managing it for continuous view was the harder one, and the same for a single pair of pages at a time would be a subcase of it. I fear I don't entirely follow the explanation about 2 separate zooms requiring split windows as we now appear to have those 2 separate zoom levels side by side, albeit only in continuous model. I'll stop here unless anyone thinks there's more I can usefully add.

**Comment by GitHubRulesOK** [comment]
Sam you are correct to point out the issue is not entirely resolved, However this niche requirement to solve height difference is way beyond most users needs (CAD users may find it most useful)
The more frequent need to maintain common width was more easily achieved for continuous modes

**Comment by GitHubRulesOK** [comment]
@kjk do you wish to re-open as the need to fit screen width or zooming in breaks the re-scaling

**Comment by sam892** [comment]
In the hopes it helps explain, I'm not expecting to pan. I'd like Fit Page/Content (Ctrl + 0 or 3) plus Facing/Book View (Ctrl + 7 or 8) to make better use of otherwise blank space, rather than shrinking the smaller of two pages more than is needed as it does at present.

Fit Content seems to achieve this when the pages are landscape, which might be a useful clue for someone. Neither Fit Page nor Fit Content achieve it for portrait pictures such as @dbent provided. I'm not sure what the difference between Fit Page and Fit content is supposed to be. (That's probably something I'd best ask on the discussion board.)

To take dbent's example picture, the blue page should be larger on screen.

Hopefully reasonably clear what we'd like now, although possibly quite complicated to code.

**Comment by GitHubRulesOK** [comment]
@sam892 
A sample file is always recommended since the example file above is working at Fit Page and both facing/book mode as requested (note in my continuous mode screen shots all pages are "fitting" to height and I have shown that works for both red on right and left. The oversize two have both been reduced in scale to match the smallest height. As you say this is good for both landscape pages and portrait sample as supplied.

**Comment by sam892** [comment]
@dbent's example file illustrates the problem nicely, it's just a matter of what settings are used when viewing. Open it with "Facing" but without "Show Pages Continuously" selected.
