### ISSUE TITLE
Stability of latest builds

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1245]
I am attaching a known problem file from MuPDF Bugzilla
Previous pre-release could not handle the content but did not crash easily.
At worst it just sat there with "Please wait - rendering" message).

Current daily build 11300 will crash when attempting to open the same file

[poor sample.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3855535/poor.sample.zip)

**Comment by GitHubRulesOK** [comment]
Whilst checking known buggy files I also found clicking on bookmark in this file will shut current x64 build 11300

[bad bookmark-mupdf696478.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3855581/bad.bookmark-mupdf696478.pdf)

**Comment by kjk** [comment]
Thanks for the samples.

The crash in 'bad bookmark' is now fixed.

During mupdf port I completely bused XPS support. Will fix.

**Comment by GitHubRulesOK** [comment]
@kjk whilst testing the installer in latest artifact (commit 232b3eb) the above bad bookmark file using a double click on the bookmark still crashes sumatraPDF

**Comment by kjk** [comment]
Bad bookmark should be fixed for real now.

**Comment by GitHubRulesOK** [comment]
@kjk confirmed that latest artefact does not misbehave with bad bookmark on this installation so have removed the example above so just waiting for (o)xps to be resolved

**Comment by kjk** [comment]
Created an issue about XPS: #1271
All other things listed here seem to be fixed.
