### ISSUE TITLE
Latest build may still have difficulties with PDF bookmarks

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1261]
Whilst testing some old issues the sample in issue https://github.com/sumatrapdfreader/sumatrapdf/issues/416 proved to be a poorly constructed PDF , nevertheless MuPDF will simply bypass rendering those pages the bulk of the file is valid thus in MuPDF and previous SumatraPDF releases the bookmarks were functional.

SumatraPDF build 3.2.11332 does not display the bookmarks

In other cases when changing setting UseTabs = false the bookmark window is not "normal" unless the whole application is restarted
![image](https://user-images.githubusercontent.com/12754913/69439369-b2f8ba80-0d3e-11ea-8b01-fc1d1965c564.png)

**Comment by kjk** [comment]
I've seen the bad bookmarks display like that but couldn't reproduce it so far.

Do you have a sequence of steps that reliably reproduces the shrunken bookmarks display?

The file in the screenshot doesn't seem to come from #416

**Comment by GitHubRulesOK** [comment]
@kjk bug.pdf came from issue 353 related to poor bookmark numbering the display issue seems to be down to a lag in refresh after swiching options tabs to unchecked application closure is thus required to rebuild bookmark canvas ?

**Comment by kjk** [comment]
I think I fixed it recently.

**Comment by GitHubRulesOK** [comment]
@kjk 
I combined two issues here that I thought relelated at the time
The secondary issue of canvas shape I have not seen recently so agree that is not a current issue
However the original issue still persists
The sample above is faulty thus one can argue we should not use it as a special case however the core issue was that there were both bad pages and **bad bookmarks** in a section of the file that previously were "bypassed" / ignored by version 3.1.2.
Llooking at the image you can see the TOC and rendering continue after the "bad" section
![image](https://user-images.githubusercontent.com/12754913/71641397-579dde80-2c93-11ea-9104-a3bf388ecb7b.png)

Current builds appear to be affected by this poor file and do not show a TOC

**Comment by kjk** [comment]
I'm not sure what problem you're referring to. There is no test file in this issue. Please open a new issue, attach the repro file etc.

Let's not put multiple things into a single issue.
