### ISSUE TITLE
Sumatrapdf crashed opening manual of mpv media player

### ISSUE THREAD

**Issue by TheMoominTroll** [sumatrapdfreader/sumatrapdf#1972]
https://gist.github.com/TheMoominTroll/3a37bf50d8bffdbd57620afa8d8e2277

**Comment by GitHubRulesOK** [comment]
@kjk 
I do not know what the current rate of crashes may be but during an install case , would it be worth the install file include dbg files?
I guess Portable users would not want the baggage unless you can place a download reminder on its start-up page

**Comment by kjk** [comment]
```
Crashed thread:
000000013F686654 01:0000000000165654 sumatrapdf.exe
000000013F6470F2 01:00000000001260F2 sumatrapdf.exe
000000013F6471E5 01:00000000001261E5 sumatrapdf.exe

HttpGet: url: 'https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/daily/SumatraPDF-prerel-13389-64.pdb.lzsa'
HttpGet: InternetOpenUrl failed
```

Unfortunately the crash report doesn't have enough information to investigate because symbols failed to download.

Does it happen every time with this file? If yes, please provide the file and steps to reproduce the crash as described in https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

**Comment by kjk** [comment]
@GitHubRulesOK I don't want to make everyone download symbols for the few times that the program crashes.

**Comment by TheMoominTroll** [comment]
> Does it happen every time with this file? If yes, please provide the file and steps to reproduce the crash as described in https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

No, only for mpv manual.
Manual : https://drive.google.com/file/d/1CuY51dpbEBnZMaqT7r9ghx7SW19Vs87-/view?usp=sharing

**Comment by kjk** [comment]
I can reproduce it in 13389 but it's already fixed in latest daily build 13397, most likely by https://github.com/sumatrapdfreader/sumatrapdf/commit/46ffda447f933d62970abadb06c237e7f61449af

Please upgrade to latest daily build https://www.sumatrapdfreader.org/dailybuilds and re-open the bug if it still happens after that.

**Comment by TheMoominTroll** [comment]
https://gist.github.com/TheMoominTroll/30babcb811e943264394c33404225882 
@kjk  still exists in  latest daily build 13397.
I switched back to stable release and it was fixed there. But there (stable build) i don't have ability to turn off scrollbar.
On stable build it shows cant download symbols.

**Comment by kjk** [comment]
@TheMoominTroll based on the callstack, it's a different crash. However, the symbols failed to download again, so the callstack doesn't say much.

Could you launch sumatra and use `Debug / Download Symbols` menu to ensure symbols are downloaded.

Then reproduce the crash and submit the crash report.
