### ISSUE TITLE
Command Palette incorrectly display position in multiply monitor

### ISSUE THREAD

**Issue by DirtyRenderingMan** [sumatrapdfreader/sumatrapdf#2678]
For example, The SumatraPdf opened in Monitor2 that is extending Display, enter **CTRL+K** the Command Palette incorrectly display in Monitor1 that is main display.

**Comment by GitHubRulesOK** [comment]
you are lucky in my set-up it blocks the viewer

@kjk if adjusting for active monitor, can it also allow for place out of main view ?

**Comment by kjk** [comment]
I don't have a multi-monitor setup to test.

I've made a change that might (or might not) fix it.

Could you check with latest pre-release 15143 or later (https://www.sumatrapdfreader.org/prerelease) ?

**Comment by DirtyRenderingMan** [comment]
@kjk I check the pre-release 15143 version. The issue is fixed. Thank you~

**Comment by ImSpecial** [comment]
I'm still getting this... On v3.4.6, I saw the fix about the "about Window" and multi monitors hoping this would be fixed but the Command Palette still always opens on my primary monitor when Sumatra otherwise is always open on my second one.

**Comment by kjk** [comment]
@ImSpecial  all the fixes done now will only be in 3.5 pre-release. Only crashes will be fixed in 3.4.* minor releases.

**Comment by ImSpecial** [comment]
Oh, so pre-release is the 3.5.x branch, gotcha.
