### ISSUE TITLE
Touch mode - Bigger icons/tabs

### ISSUE THREAD

**Issue by Mitia99** [sumatrapdfreader/sumatrapdf#3813]
Dear dev,

Ty for considering an option to have bigger icons and tabs for a better touchscreen experience.

**Comment by kjk** [comment]
You can use `ToolbarSize` advanced setting to change size of icons.

**Comment by Mitia99** [comment]
> You can use `ToolbarSize` advanced setting to change size of icons.

Ty for the tip. It doesn't solve the issue though. Page number is not full displayed, Tabs aren't bigger (I also edited `TabWidth` advanced setting).
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/56766778/b2de4948-4439-433a-ade6-4e9c5e9762e4)

And it doesn't make menu items any bigger
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/56766778/4c8c70df-679a-4672-81af-7e218f5c8fe6)

**Comment by kjk** [comment]
I fixed the issue with text box and `ToolbarSize` in latest [pre-release](https://www.sumatrapdfreader.org/prerelease)

**Comment by GitHubRulesOK** [comment]
Looks good in Watchman theme :-)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/06fdc935-3e86-4f0a-b2e6-d68bc92594b8)

**Comment by Mitia99** [comment]
> I fixed the issue with text box and `ToolbarSize` in latest [pre-release](https://www.sumatrapdfreader.org/prerelease)

There is still the same issue in latest pre-release.
![Toolbar](https://github.com/sumatrapdfreader/sumatrapdf/assets/56766778/4d2606bb-573f-447c-bf39-70d60d91f6a0)

**Comment by kjk** [comment]
@Mitia99 please specify the version. It takes up to 24 hrs for the pre-release to be updated since the moment I make a change. It should be fixed in 15861 or later

**Comment by Mitia99** [comment]
> @Mitia99 please specify the version. It takes up to 24 hrs for the pre-release to be updated since the moment I make a change. It should be fixed in 15861 or later

Version used is `3.6.15861` Pre-release

**Comment by kjk** [comment]
I cannot reproduce this.

What is the `ToolbarSize` value? 

Did you change the size of default Windows' font? We scale the size of the font used on toolbar based on default size of Windows font. It's possible if you've changed the size it would get too big. Will try to fix such case.

**Comment by Mitia99** [comment]
> I cannot reproduce this.
> 
> What is the `ToolbarSize` value? 
> 
> Did you change the size of default Windows' font? We scale the size of the font used on toolbar based on default size of Windows font. It's possible if you've changed the size it would get too big. Will try to fix such case.

My Windows 11 display default scale is 200%(It's a 12.6" tablet). I think it is what causing the issue. Tried to lower it to 100% and there was no issue.

Ty for investigating,

**Comment by kjk** [comment]
I've made a change that should fix it, should be available in pre-release in less than 24hrs.

**Comment by GitHubRulesOK** [comment]
looking better
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4e8cf4ca-f8fd-4af3-ac73-913c8ea4fdee)

**Comment by Mitia99** [comment]
> I've made a change that should fix it, should be available in pre-release in less than 24hrs.

Ty. It's better in `3.6.15869`. A fix is still needed for `g` letter which is cut on input. 
**Toolbarsize** 60
**Display scale** 200%
![tt](https://github.com/sumatrapdfreader/sumatrapdf/assets/56766778/c7617179-1f8c-47a1-b7c8-1f8e08658e1b)

**Comment by kjk** [comment]
I assume this is fixed.
