### ISSUE TITLE
PDF link goes to the wrong place

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3860]
I have attached a sample document below, created in Altium Designer version 23.8.1, that exhibits the behavior I mentioned. I am using b49630b (the current prerelease version).

The links appear to work correctly with this particular pdf while using:
- Acrobat Reader: 2023.006.20360
- Microsoft Edge: 118.0.2088.76 (Official build) (64-bit) 
- Google Chrome: 119.0.6045.123 (Official Build) (64-bit) (cohort: M119 Rollout) 

[PCB_Project.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13291128/PCB_Project.pdf)

The green rectangles on the first page are supposed to link to the specified sheet. I noticed that the highlighted/selected bookmark appears to be correct after clicking a link, but the bookmarks also appear to correspond to the incorrect sheet.

Please let me know if I can help in any way or provide any more information.

_Originally posted by @sullivanmj in https://github.com/sumatrapdfreader/sumatrapdf/issues/2692#issuecomment-1800884263_

**Comment by kjk** [comment]
The link is: `#page=2&viewrect=0,612,792,-612`

It's arguably broken: it sets y position as 612 and then dy as minus 612.

It should be y=0 and presumably dy=612. Or maybe dy=0

After parsing with `fz_resolve_link()` we get:
```
x=0.00000000
y=612.000000
dx=792.000000
dy=0.00000000
```
so we scroll to y=612 which is end of page.

**Comment by kjk** [comment]
Opened https://bugs.ghostscript.com/show_bug.cgi?id=707313

**Comment by GitHubRulesOK** [comment]
@kjk 
I dont see where in PDF syntax -612 applies 
the trace for links starts with page
`<</Type /Page /Parent 1 0 R /Group <</CS /DeviceRGB /S /Transparency>> /Resources 48 0 R /Contents [49 0 R]
/MediaBox [0 0 792 612]
/Annots [
35 0 R
37 0 R
39 0 R
] >>`

so the links are clearly there as 35 37 39 which in turn like this one
`35 0 obj <</Type /Annot /Subtype /Link /Border [] /F 0 /C [1 1 0 ] /Rect [496 423 568 471] /A 34 0 R >>`

lead to the number before so 34 36 38 which clearly state use full page 26 10 18 (=page 2 3 4)
```
34 0 obj
<</S /GoTo /D [26 0 R /FitR 0 612 792 0] >>
endobj
36 0 obj
<</S /GoTo /D [10 0 R /FitR 0 612 792 0] >>
endobj
38 0 obj
<</S /GoTo /D [18 0 R /FitR 0 612 792 0] >>
```

the problem seems to be that in continuous mode that go is used as if from top where as it should scroll the whole page into view here is how tracker reads the instructions 1st as text then as you say its  different visually looks like lower but the result is show the page
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d5597d41-27a0-406e-bb6a-6653d54b37d3)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f1b838b4-7ae2-4a87-924c-a278044c66d9)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/78f0b518-7579-4f54-9c34-b69f6e3979fe)

**Comment by kjk** [comment]
hmm, maybe mupdf parses it incorrectly. will have to look deeper

**Comment by kjk** [comment]
fixed by mupdf update

**Comment by miguelfazenda** [comment]
Hello! I still have this issue with SumatraPDF v3.5.2.
I have tried it with the example file posted by kjk.

**Comment by kjk** [comment]
Fixes are only available in latest pre-release https://www.sumatrapdfreader.org/prerelease
