### ISSUE TITLE
Silent "all users" installation of SumatraPDF 3.5.2 fails if not in admin CMD

### ISSUE THREAD

**Issue by bfg01** [sumatrapdfreader/sumatrapdf#4559]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
Trying to install in "silent" mode for all users instead of default user via command line; this fails if CMD was not run as administrator beforehand.
Whether successful or failed, there is no output in command line, but if echoing variable "%errorlevel%" after running the command it outputs plain '0' when successful and plain '1' when failed.
I know this should be a logical result, but I actually expected for SumatraPDF installer to call UAC in case CMD session was not admin.

**To Reproduce**
1. Open CMD as normal user
2. SumatraPDF-3.5.2-64-install.exe -s -all-users -with-filter -with-preview
3. echo %errorlevel%
4. See if anything is installed

**Expected behavior**
For SumatraPDF to call UAC in case CMD session is not admin

**File that reproduces the problem**
Not applicable

**Screenshots**
Not applicable

**Additional context**
Not applicable

**Comment by GitHubRulesOK** [comment]
silent means no feedback in most apps thus I personally would expect same as for printing dont use silent or else you cant see what is failing. 

If a user environment is not elevated then dont run as "all users" without  admin password somewhere in the mix.
```
RUNAS USAGE:

RUNAS [ [/noprofile | /profile] [/env] [/savecred | /netonly] ]
        /user:<UserName> program

RUNAS [ [/noprofile | /profile] [/env] [/savecred] ]
        /smartcard [/user:<UserName>] program

RUNAS /trustlevel:<TrustLevel> program

   /noprofile        specifies that the user's profile should not be loaded.
                     This causes the application to load more quickly, but
                     can cause some applications to malfunction.
   /profile          specifies that the user's profile should be loaded.
                     This is the default.
   /env              to use current environment instead of user's.
   /netonly          use if the credentials specified are for remote
                     access only.
   /savecred         to use credentials previously saved by the user.
   /smartcard        use if the credentials are to be supplied from a
                     smartcard.
   /user             <UserName> should be in form USER@DOMAIN or DOMAIN\USER
   /showtrustlevels  displays the trust levels that can be used as arguments
                     to /trustlevel.
   /trustlevel       <Level> should be one of levels enumerated
                     in /showtrustlevels.
   program         command line for EXE.  See below for examples
```

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kjk** [comment]
This is fixed in pre-release. `-install -s -all-users` will elevate if needed

**Comment by stuartm-hm** [comment]
This still doesn't work properly. I can install SumatraPDF on my local machine using the prerelease version with "-s -all-users". If I enter a remote powershell session or use a deployment too like PDQ deploy then it doesn't work. (I always installed previous versions this way with /S and it worked fine.)

`[remote-pc]: PS C:\> .\SumatraPDF-prerel-64-install.exe -all-users -s
ParseFlags: argName: '-all-users', arg: 65
ParseFlags: argName: '-s', arg: 0
Starting: '"C:\SumatraPDF-prerel-64-install.exe" -all-users -s'
  ver 17065, flags.install: 0, flags.uninstall: 0
------------- Starting SumatraPDF installation
OpenEmbeddedFilesArchive: opened archive
GetExistingInstallationDir()
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
ReadRegStrTemp(HKEY_CLASSES_ROOT, .pdf\PersistentHandler, (null)) => '(null)'
IsSearchFilterInstalled() isInstalled=0
ReadRegStrTemp(HKEY_CLASSES_ROOT, .pdf\shellex\{8895b1c6-b41f-4c1c-a562-0d564250836f}, (null)) => '(null)'
IsPreviewInstalled() isInstalled=0
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
GetPreviousInstallInfo: dir 'C:\Users\pdqadmin\AppData\Local\SumatraPDF', search filter: 0, preview: 0, typ: 2, needsElevation: 1
HasPreviousInstall(): hasPrev: 1
!gCli->runInstallNew so inheriting prev install state
GetDefaultInstallationDir(forAllUsers=1, ignorePrev=0)
  using C:\Users\pdqadmin\AppData\Local\SumatraPDF from previous install`

I noticed the last line in particular. I tried to deploy the software with PDQ deploy unsuccessfully, then tried again with powershell remoting. Pdqadmin is an account used specifically with PDQ deploy. I ran the remote powershell session with my own personal admin account. I guess something from the previous install is affecting the new install.

`[remote-pc]: PS C:\> .\SumatraPDF-prerel-64-install.exe -uninstall
ParseFlags: argName: '-uninstall', arg: 17
Starting: '"C:\SumatraPDF-prerel-64-install.exe" -uninstall'
  ver 17065, flags.install: 0, flags.uninstall: 1
GetExistingInstallationDir()
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
Running uninstaller 'C:\SumatraPDF-prerel-64-install.exe' with args '"C:\SumatraPDF-prerel-64-install.exe" -uninstall' for 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
RelaunchMaybeElevatedFromTempDirectory()
  copying installer 'C:\SumatraPDF-prerel-64-install.exe' to 'C:\Users\stuartm\AppData\Local\Temp\Sumatra-Uninstaller.exe'
LaunchProcessWithCmdLine('C:\Users\stuartm\AppData\Local\Temp\Sumatra-Uninstaller.exe' '-uninstall')
LaunchProcessWithCmdLine() launched 'C:\Users\stuartm\AppData\Local\Temp\Sumatra-Uninstaller.exe' '-uninstall' ok!

[remote-pc]: PS C:\> .\SumatraPDF-prerel-64-install.exe -s -all-users
ParseFlags: argName: '-s', arg: 0
ParseFlags: argName: '-all-users', arg: 65
Starting: '"C:\SumatraPDF-prerel-64-install.exe" -s -all-users'
  ver 17065, flags.install: 0, flags.uninstall: 0
------------- Starting SumatraPDF installation
OpenEmbeddedFilesArchive: opened archive
GetExistingInstallationDir()
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
ReadRegStrTemp(HKEY_CLASSES_ROOT, .pdf\PersistentHandler, (null)) => '(null)'
IsSearchFilterInstalled() isInstalled=0
ReadRegStrTemp(HKEY_CLASSES_ROOT, .pdf\shellex\{8895b1c6-b41f-4c1c-a562-0d564250836f}, (null)) => '(null)'
IsPreviewInstalled() isInstalled=0
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
GetPreviousInstallInfo: dir 'C:\Users\pdqadmin\AppData\Local\SumatraPDF', search filter: 0, preview: 0, typ: 2, needsElevation: 1
HasPreviousInstall(): hasPrev: 1
!gCli->runInstallNew so inheriting prev install state
GetDefaultInstallationDir(forAllUsers=1, ignorePrev=0)
  using C:\Users\pdqadmin\AppData\Local\SumatraPDF from previous install
Running'C:\SumatraPDF-prerel-64-install.exe', cmdLine: '"C:\SumatraPDF-prerel-64-install.exe" -s -all-users', installing into dir 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
RunInstaller: gCliNew.silent: 1, gCliNew.allUsers: 1, gCliNew.runInstallNow: 0, gCliNew.withFilter: 0, gCliNew.withPreview: 0, gCliNew.fastInstall: 0
InstallerThread: cli->allUsers: 1, cli->withFilter: 0, cli->withPreview: 0, installerExePath: 'C:\Users\pdqadmin\AppData\Local\SumatraPDF\SumatraPDF.exe'
ExtractInstallerFiles() to 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'
CopySelfToDir(C:\Users\pdqadmin\AppData\Local\SumatraPDF)
  copied 'C:\SumatraPDF-prerel-64-install.exe' to dir 'C:\Users\pdqadmin\AppData\Local\SumatraPDF'`

Here I ran the uninstaller first and I still get the same issue. The user "pdqadmin" is not being used for the install but it still references that account.

HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation

This key is getting left behind it seems, I've not tried deleting it first but I guess that could be it.
